package com.snail.dao;

import com.snail.entity.SysRolePermissionExample;
import com.snail.entity.SysRolePermissionKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int countByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int deleteByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int deleteByPrimaryKey(SysRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int insert(SysRolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int insertSelective(SysRolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    List<SysRolePermissionKey> selectByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysRolePermissionKey record, @Param("example") SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbggenerated Wed Apr 03 22:44:42 CST 2019
     */
    int updateByExample(@Param("record") SysRolePermissionKey record, @Param("example") SysRolePermissionExample example);
}