server:
  port: 8761

eureka:
  instance:
    hostname: eureka #定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 5000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: true #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka,http://admin:123456@127.0.0.1:8762/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  security:
    user:
      name: admin
      password: 123456
